### ISSUE TITLE
Icon in Sidebar is missing 

### ISSUE THREAD

**Issue by michaelmassee** [WollMux/WollMux#189] opened 2020-01-31 17:26 UTC
Hallo,
after updating from Lo 6.2 to 6.3, the Sidebar-Icon is missing.

![Auswahl_137](https://user-images.githubusercontent.com/35254212/73560388-257cc980-4457-11ea-87a7-8d84feefb0d3.png)

regards

**Comment by michaelweghorn** [comment] 2020-02-03 08:52
Thanks for your reporting.
This looks like a LibreOffice issue and I realized that you have already submitted a bug report at https://bugs.documentfoundation.org/show_bug.cgi?id=130310 . I've added an additional information on the commit that introduced the regression there.

**Comment by michaelweghorn** [comment] 2020-03-26 13:24
Let's close this issue here. LibreOffice just received a fix as well.

**Closed by michaelweghorn** 2020-03-26 13:24 UTC
